# Generated by Django 2.2.1 on 2019-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
